spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/javajpa
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate:
        ddlauto: update
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect